First run tests before publishing

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -6,6 +6,35 @@ on:
       - 'v*'
 
 jobs:
+  tests:
+    name: Linting and running tests
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v4
+    - name: Install poetry
+      run: pip install poetry
+    - name: Install dependencies
+      run: poetry install
+    - name: Run Pylint
+      run: |
+        poetry run pylint --fail-under=9 --rcfile=.pylintrc aikido_firewall/
+        pylint_exit_code=$?
+        if [ $pylint_exit_code -ne 0 ]; then
+          echo "Pylint check failed. Please fix the issues."
+          exit 1
+        fi
+
+    - name: Run Black Check
+      run: |
+        poetry run black --check --diff aikido_firewall/
+        black_exit_code=$?
+        if [ $black_exit_code -ne 0 ]; then
+          echo "Black check failed. Please run 'black .' to format the code."
+          exit 1
+        fi
+    - name: Run tests
+      run: |
+        make test
   build:
     name: Build distribution 📦
     runs-on: ubuntu-latest
